package GUI;

public class GUI_Administrador extends javax.swing.JFrame {
    
    public GUI_Administrador(){
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        administradorLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modificarUsuario = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        crearUsuario = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JLabel();
        administradorLabel2 = new javax.swing.JLabel();
        bienvenidoLabel = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(108, 101, 247));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><body> <center>  Reportes y<br>Consultas </center></body></html>");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(580, 250, 140, 90);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 101, 247));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html><body> <center>  Modificar<br>Usuario </center></body></html>");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 250, 140, 90);

        administradorLabel.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        administradorLabel.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel.setText("Administrador");
        jPanel1.add(administradorLabel);
        administradorLabel.setBounds(140, 50, 200, 50);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(108, 101, 247));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><body> <center>  Crear<br>Usuario </center></body></html>");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(238, 250, 150, 90);

        modificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        modificarUsuario.setBorder(null);
        modificarUsuario.setBorderPainted(false);
        modificarUsuario.setContentAreaFilled(false);
        modificarUsuario.setFocusPainted(false);
        modificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(modificarUsuario);
        modificarUsuario.setBounds(400, 240, 160, 110);

        reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        reportes.setBorder(null);
        reportes.setBorderPainted(false);
        reportes.setContentAreaFilled(false);
        reportes.setFocusPainted(false);
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        jPanel1.add(reportes);
        reportes.setBounds(570, 240, 160, 110);
        reportes.getAccessibleContext().setAccessibleName("Reportes y Consultas");

        crearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        crearUsuario.setBorder(null);
        crearUsuario.setBorderPainted(false);
        crearUsuario.setContentAreaFilled(false);
        crearUsuario.setFocusPainted(false);
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(crearUsuario);
        crearUsuario.setBounds(230, 240, 160, 110);

        CerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(CerrarSesion);
        CerrarSesion.setBounds(610, 60, 120, 30);

        administradorLabel2.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        administradorLabel2.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setText("Administrador");
        jPanel1.add(administradorLabel2);
        administradorLabel2.setBounds(40, 280, 200, 50);

        bienvenidoLabel.setBackground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setText("  Bienvenido ");
        jPanel1.add(bienvenidoLabel);
        bienvenidoLabel.setBounds(40, 240, 200, 50);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdministrador1.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 760, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        
        /*GUI_ReportesAdmin interfazReportesAdmin = new GUI_ReportesAdmin();
        interfazReportesAdmin.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_reportesActionPerformed
    
    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        
        /*GUI_CrearUsuario interfazCrearUsuario = new GUI_CrearUsuario();
        interfazCrearUsuario.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_crearUsuarioActionPerformed
    
    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        
        GUI_Login interfazLogin = new GUI_Login();
        interfazLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionMouseClicked
    
    private void modificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarUsuarioActionPerformed
        
        /*GUI_ModificarUsuario interfazModificarUsuario = new GUI_ModificarUsuario();
        interfazModificarUsuario.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_modificarUsuarioActionPerformed
    
    public static void main(String args[]){
       
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run(){
                
                new GUI_Administrador().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel administradorLabel;
    private javax.swing.JLabel administradorLabel2;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JButton crearUsuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarUsuario;
    private javax.swing.JButton reportes;
    // End of variables declaration//GEN-END:variables
}