package GUI;

public class GUI_Administrador extends javax.swing.JFrame {
    
    public GUI_Administrador(){
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        administradorLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modificarEmpleado = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        registrarEnfermera = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JLabel();
        administradorLabel2 = new javax.swing.JLabel();
        bienvenidoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registrarMedico = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        crearPaciente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        modificarPaciente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        modificarCita = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        registrarMedicamento = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        registrarCampana = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(108, 101, 247));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><body> <center>  Reportes y<br>Consultas </center></body></html>");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(580, 250, 140, 90);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 101, 247));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html><body> <center>  Modificar<br>Empleado </center></body></html>");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(410, 250, 140, 90);

        administradorLabel.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        administradorLabel.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel.setText("Administrador");
        jPanel1.add(administradorLabel);
        administradorLabel.setBounds(140, 50, 200, 50);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(108, 101, 247));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><body> <center>  Crear<br>Usuario </center></body></html>");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(238, 250, 150, 90);

        modificarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        modificarEmpleado.setBorder(null);
        modificarEmpleado.setBorderPainted(false);
        modificarEmpleado.setContentAreaFilled(false);
        modificarEmpleado.setFocusPainted(false);
        modificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(modificarEmpleado);
        modificarEmpleado.setBounds(400, 240, 160, 110);

        reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        reportes.setBorder(null);
        reportes.setBorderPainted(false);
        reportes.setContentAreaFilled(false);
        reportes.setFocusPainted(false);
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        jPanel1.add(reportes);
        reportes.setBounds(570, 240, 160, 110);
        reportes.getAccessibleContext().setAccessibleName("Reportes y Consultas");

        registrarEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        registrarEnfermera.setBorder(null);
        registrarEnfermera.setBorderPainted(false);
        registrarEnfermera.setContentAreaFilled(false);
        registrarEnfermera.setFocusPainted(false);
        registrarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEnfermeraActionPerformed(evt);
            }
        });
        jPanel1.add(registrarEnfermera);
        registrarEnfermera.setBounds(230, 240, 160, 110);

        CerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(CerrarSesion);
        CerrarSesion.setBounds(610, 60, 120, 30);

        administradorLabel2.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        administradorLabel2.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setText("Administrador");
        jPanel1.add(administradorLabel2);
        administradorLabel2.setBounds(40, 280, 200, 50);

        bienvenidoLabel.setBackground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setText("  Bienvenido ");
        jPanel1.add(bienvenidoLabel);
        bienvenidoLabel.setBounds(40, 240, 200, 50);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(108, 101, 247));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html><body> <center>  Crear<br>Medico </center></body></html>");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(410, 140, 140, 90);

        registrarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        registrarMedico.setBorder(null);
        registrarMedico.setBorderPainted(false);
        registrarMedico.setContentAreaFilled(false);
        registrarMedico.setFocusPainted(false);
        registrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(registrarMedico);
        registrarMedico.setBounds(400, 130, 160, 110);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 101, 247));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html><body> <center>  Crear<br>Paciente </center></body></html>");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 140, 140, 90);

        crearPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        crearPaciente.setBorder(null);
        crearPaciente.setBorderPainted(false);
        crearPaciente.setContentAreaFilled(false);
        crearPaciente.setFocusPainted(false);
        crearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(crearPaciente);
        crearPaciente.setBounds(570, 130, 160, 110);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(108, 101, 247));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html><body> <center>  Modificar<br>Paciente </center></body></html>");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 370, 140, 90);

        modificarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        modificarPaciente.setBorder(null);
        modificarPaciente.setBorderPainted(false);
        modificarPaciente.setContentAreaFilled(false);
        modificarPaciente.setFocusPainted(false);
        modificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(modificarPaciente);
        modificarPaciente.setBounds(230, 360, 160, 110);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 101, 247));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html><body> <center>  Modificar<br>Cita </center></body></html>");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(410, 370, 140, 90);

        modificarCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        modificarCita.setBorder(null);
        modificarCita.setBorderPainted(false);
        modificarCita.setContentAreaFilled(false);
        modificarCita.setFocusPainted(false);
        modificarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarCitaActionPerformed(evt);
            }
        });
        jPanel1.add(modificarCita);
        modificarCita.setBounds(400, 360, 160, 110);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(108, 101, 247));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<html><body> <center>  Registrar<br>Medicamento </center></body></html>");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(580, 370, 140, 90);

        registrarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        registrarMedicamento.setBorder(null);
        registrarMedicamento.setBorderPainted(false);
        registrarMedicamento.setContentAreaFilled(false);
        registrarMedicamento.setFocusPainted(false);
        registrarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMedicamentoActionPerformed(evt);
            }
        });
        jPanel1.add(registrarMedicamento);
        registrarMedicamento.setBounds(570, 360, 160, 110);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(108, 101, 247));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html><body> <center>  Registrar<br>Campaña </center></body></html>");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(240, 140, 140, 90);

        registrarCampana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        registrarCampana.setBorder(null);
        registrarCampana.setBorderPainted(false);
        registrarCampana.setContentAreaFilled(false);
        registrarCampana.setFocusPainted(false);
        registrarCampana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCampanaActionPerformed(evt);
            }
        });
        jPanel1.add(registrarCampana);
        registrarCampana.setBounds(230, 130, 160, 110);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdministrador1.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 760, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        
        GUI_CrearArea med = new GUI_CrearArea();
        med.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportesActionPerformed
    
    private void registrarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEnfermeraActionPerformed
        
        GUI_CrearEnfermera interfazCrearEnfermera = new GUI_CrearEnfermera();
        interfazCrearEnfermera.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarEnfermeraActionPerformed
  
    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        
        GUI_Login interfazLogin = new GUI_Login();
        interfazLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionMouseClicked
    
    private void modificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEmpleadoActionPerformed
        
        GUI_ModificarEmpleado interfazModificarEmpleado = new GUI_ModificarEmpleado();
        interfazModificarEmpleado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarEmpleadoActionPerformed

    private void registrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMedicoActionPerformed
        // TODO add your handling code here:
        GUI_CrearMedico interfazCrearMedico = new GUI_CrearMedico();
        interfazCrearMedico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarMedicoActionPerformed

    private void crearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPacienteActionPerformed
        // TODO add your handling code here:
        GUI_CrearPaciente interfazCrearPaciente = new GUI_CrearPaciente();
        interfazCrearPaciente.setTipo("Administrador");
        interfazCrearPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearPacienteActionPerformed

    private void modificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPacienteActionPerformed
        // TODO add your handling code here:
        GUI_ModificarPaciente interfazModificarPaciente = new GUI_ModificarPaciente();
        interfazModificarPaciente.setTipo("Administrador");
        interfazModificarPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarPacienteActionPerformed

    private void modificarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarCitaActionPerformed
        GUI_ModificarCita interfazModificarCita = new GUI_ModificarCita();
        interfazModificarCita.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarCitaActionPerformed

    private void registrarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMedicamentoActionPerformed
        GUI_RegistrarMedicamento i = new GUI_RegistrarMedicamento();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarMedicamentoActionPerformed

    private void registrarCampanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCampanaActionPerformed
     /*   GUI_RegistrarCampana i = new GUI_RegistrarCampana();
        i.setVisible(true);
        this.dispose();*/
     GUI_ModificarCampana i = new GUI_ModificarCampana();
     i.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_registrarCampanaActionPerformed
    
    public static void main(String args[]){
       
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run(){
                
                new GUI_Administrador().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel administradorLabel;
    private javax.swing.JLabel administradorLabel2;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JButton crearPaciente;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarCita;
    private javax.swing.JButton modificarEmpleado;
    private javax.swing.JButton modificarPaciente;
    private javax.swing.JButton registrarCampana;
    private javax.swing.JButton registrarEnfermera;
    private javax.swing.JButton registrarMedicamento;
    private javax.swing.JButton registrarMedico;
    private javax.swing.JButton reportes;
    // End of variables declaration//GEN-END:variables
}