package GUI;

public class GUI_InterfazInformes extends javax.swing.JFrame {

    private String tipo;
    
    public GUI_InterfazInformes(){
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        administradorLabel = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JLabel();
        administradorLabel2 = new javax.swing.JLabel();
        bienvenidoLabel = new javax.swing.JLabel();
        agendaLabel = new javax.swing.JLabel();
        agendaBoton = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(null);

        administradorLabel.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        administradorLabel.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel.setText("Informes");
        jPanel1.add(administradorLabel);
        administradorLabel.setBounds(140, 50, 200, 50);

        CerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(CerrarSesion);
        CerrarSesion.setBounds(610, 60, 120, 30);

        administradorLabel2.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        administradorLabel2.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setText("Administrador");
        jPanel1.add(administradorLabel2);
        administradorLabel2.setBounds(40, 280, 200, 50);

        bienvenidoLabel.setBackground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setText("  Bienvenido ");
        jPanel1.add(bienvenidoLabel);
        bienvenidoLabel.setBounds(40, 240, 200, 50);

        agendaLabel.setBackground(new java.awt.Color(255, 255, 255));
        agendaLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        agendaLabel.setForeground(new java.awt.Color(108, 101, 247));
        agendaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agendaLabel.setText("<html><body> <center> Agenda </br> Medicos</center></body></html>");
        jPanel1.add(agendaLabel);
        agendaLabel.setBounds(260, 170, 140, 90);

        agendaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        agendaBoton.setBorder(null);
        agendaBoton.setBorderPainted(false);
        agendaBoton.setContentAreaFilled(false);
        agendaBoton.setFocusPainted(false);
        agendaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaBotonActionPerformed(evt);
            }
        });
        jPanel1.add(agendaBoton);
        agendaBoton.setBounds(250, 160, 160, 110);

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelarMed.png"))); // NOI18N
        botonCancelar.setBorder(null);
        botonCancelar.setBorderPainted(false);
        botonCancelar.setContentAreaFilled(false);
        botonCancelar.setFocusPainted(false);
        botonCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelarPeq.png"))); // NOI18N
        botonCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar);
        botonCancelar.setBounds(610, 400, 130, 70);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdministrador1.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 760, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
          
    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        
        GUI_Login interfazLogin = new GUI_Login();
        interfazLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionMouseClicked
    
    private void agendaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaBotonActionPerformed
        GUI_Agenda agenda = new GUI_Agenda(tipo);
        System.out.println(tipo);
        agenda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agendaBotonActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        if (tipo.equals("Operador")){
            GUI_Operador operador = new GUI_Operador();
            operador.setVisible(true);
            this.dispose();
        }
        else if(tipo.equals("Administrador")){
            GUI_Administrador adminLogin = new GUI_Administrador();
            adminLogin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botonCancelarActionPerformed
    
    public static void main(String args[]){
       
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run(){
                
                new GUI_InterfazInformes().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel administradorLabel;
    private javax.swing.JLabel administradorLabel2;
    private javax.swing.JButton agendaBoton;
    private javax.swing.JLabel agendaLabel;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    void setTipo(String administrador) {
        this.tipo = administrador;
    }
}