package GUI;

public class GUI_InterfazPacientes extends javax.swing.JFrame {

    private String tipo;
    
    public GUI_InterfazPacientes(){
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        administradorLabel = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JLabel();
        administradorLabel2 = new javax.swing.JLabel();
        bienvenidoLabel = new javax.swing.JLabel();
        crearPacienteLabel = new javax.swing.JLabel();
        crearPaciente = new javax.swing.JButton();
        modificarPacienteLabel = new javax.swing.JLabel();
        modificarPaciente = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(null);

        administradorLabel.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        administradorLabel.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel.setText("Pacientes");
        jPanel1.add(administradorLabel);
        administradorLabel.setBounds(140, 50, 200, 50);

        CerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(CerrarSesion);
        CerrarSesion.setBounds(610, 60, 120, 30);

        administradorLabel2.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        administradorLabel2.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setText("Administrador");
        jPanel1.add(administradorLabel2);
        administradorLabel2.setBounds(40, 280, 200, 50);

        bienvenidoLabel.setBackground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setText("  Bienvenido ");
        jPanel1.add(bienvenidoLabel);
        bienvenidoLabel.setBounds(40, 240, 200, 50);

        crearPacienteLabel.setBackground(new java.awt.Color(255, 255, 255));
        crearPacienteLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        crearPacienteLabel.setForeground(new java.awt.Color(108, 101, 247));
        crearPacienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearPacienteLabel.setText("<html><body> <center>  Registrar<br>Paciente </center></body></html>");
        jPanel1.add(crearPacienteLabel);
        crearPacienteLabel.setBounds(300, 250, 140, 90);

        crearPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        crearPaciente.setBorder(null);
        crearPaciente.setBorderPainted(false);
        crearPaciente.setContentAreaFilled(false);
        crearPaciente.setFocusPainted(false);
        crearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(crearPaciente);
        crearPaciente.setBounds(290, 240, 160, 110);

        modificarPacienteLabel.setBackground(new java.awt.Color(255, 255, 255));
        modificarPacienteLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        modificarPacienteLabel.setForeground(new java.awt.Color(108, 101, 247));
        modificarPacienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificarPacienteLabel.setText("<html><body> <center>  Modificar<br>Paciente </center></body></html>");
        jPanel1.add(modificarPacienteLabel);
        modificarPacienteLabel.setBounds(510, 250, 140, 90);

        modificarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        modificarPaciente.setBorder(null);
        modificarPaciente.setBorderPainted(false);
        modificarPaciente.setContentAreaFilled(false);
        modificarPaciente.setFocusPainted(false);
        modificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(modificarPaciente);
        modificarPaciente.setBounds(500, 240, 160, 110);

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelarMed.png"))); // NOI18N
        botonCancelar.setBorder(null);
        botonCancelar.setBorderPainted(false);
        botonCancelar.setContentAreaFilled(false);
        botonCancelar.setFocusPainted(false);
        botonCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelarPeq.png"))); // NOI18N
        botonCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar);
        botonCancelar.setBounds(610, 400, 130, 70);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdministrador1.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 760, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
          
    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        
        GUI_Login interfazLogin = new GUI_Login();
        interfazLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionMouseClicked
    
    private void crearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearPacienteActionPerformed
        // TODO add your handling code here:
        GUI_CrearPaciente interfazCrearPaciente = new GUI_CrearPaciente();
        interfazCrearPaciente.setTipo(this.tipo);
        interfazCrearPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearPacienteActionPerformed

    private void modificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarPacienteActionPerformed
        // TODO add your handling code here:
        GUI_ModificarPaciente interfazModificarPaciente = new GUI_ModificarPaciente();
        interfazModificarPaciente.setTipo(this.tipo);
        interfazModificarPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarPacienteActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        if (tipo.equals("Operador")){
            GUI_Operador operador = new GUI_Operador();
            operador.setVisible(true);
            this.dispose();
        }
        else if(tipo.equals("Administrador")){
            GUI_Administrador adminLogin = new GUI_Administrador();
            adminLogin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botonCancelarActionPerformed
    
    public static void main(String args[]){
       
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run(){
                
                new GUI_InterfazPacientes().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel administradorLabel;
    private javax.swing.JLabel administradorLabel2;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton crearPaciente;
    private javax.swing.JLabel crearPacienteLabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarPaciente;
    private javax.swing.JLabel modificarPacienteLabel;
    // End of variables declaration//GEN-END:variables

    void setTipo(String administrador) {
        this.tipo = administrador;
    }
}