package GUI;
import Controladores.ControladorOperador;
import Logica.Operador;

public class GUI_Operador extends javax.swing.JFrame {
    
        public GUI_Operador(){
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        operadorLabel2 = new javax.swing.JLabel();
        operadorLabel = new javax.swing.JLabel();
        bienvenidoLabel = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JLabel();
        citaLabel = new javax.swing.JLabel();
        citaBoton = new javax.swing.JButton();
        informeLabel = new javax.swing.JLabel();
        informesBoton = new javax.swing.JButton();
        pacienteLabel = new javax.swing.JLabel();
        pacienteBoton = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        operadorLabel2.setBackground(new java.awt.Color(255, 255, 255));
        operadorLabel2.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        operadorLabel2.setForeground(new java.awt.Color(255, 255, 255));
        operadorLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operadorLabel2.setText("Operador");
        jPanel1.add(operadorLabel2);
        operadorLabel2.setBounds(20, 280, 190, 50);

        operadorLabel.setBackground(new java.awt.Color(255, 255, 255));
        operadorLabel.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        operadorLabel.setForeground(new java.awt.Color(255, 255, 255));
        operadorLabel.setText("Operador");
        jPanel1.add(operadorLabel);
        operadorLabel.setBounds(140, 40, 200, 50);

        bienvenidoLabel.setBackground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setText("  Bienvenido(a) ");
        jPanel1.add(bienvenidoLabel);
        bienvenidoLabel.setBounds(20, 240, 200, 50);

        CerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(CerrarSesion);
        CerrarSesion.setBounds(610, 40, 120, 50);

        citaLabel.setBackground(new java.awt.Color(255, 255, 255));
        citaLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        citaLabel.setForeground(new java.awt.Color(108, 101, 247));
        citaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        citaLabel.setText("<html><body> <center>  Citas </center></body></html>");
        jPanel1.add(citaLabel);
        citaLabel.setBounds(240, 240, 140, 90);

        citaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        citaBoton.setBorder(null);
        citaBoton.setBorderPainted(false);
        citaBoton.setContentAreaFilled(false);
        citaBoton.setFocusPainted(false);
        citaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citaBotonActionPerformed(evt);
            }
        });
        jPanel1.add(citaBoton);
        citaBoton.setBounds(230, 230, 160, 110);

        informeLabel.setBackground(new java.awt.Color(255, 255, 255));
        informeLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        informeLabel.setForeground(new java.awt.Color(108, 101, 247));
        informeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informeLabel.setText("<html><body> <center>  Informes </center></body></html>");
        jPanel1.add(informeLabel);
        informeLabel.setBounds(580, 240, 140, 90);

        informesBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        informesBoton.setBorder(null);
        informesBoton.setBorderPainted(false);
        informesBoton.setContentAreaFilled(false);
        informesBoton.setFocusPainted(false);
        informesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informesBotonActionPerformed(evt);
            }
        });
        jPanel1.add(informesBoton);
        informesBoton.setBounds(570, 230, 160, 110);

        pacienteLabel.setBackground(new java.awt.Color(255, 255, 255));
        pacienteLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        pacienteLabel.setForeground(new java.awt.Color(108, 101, 247));
        pacienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pacienteLabel.setText("<html><body> <center>  Pacientes </center></body></html>");
        jPanel1.add(pacienteLabel);
        pacienteLabel.setBounds(410, 240, 140, 90);

        pacienteBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        pacienteBoton.setBorder(null);
        pacienteBoton.setBorderPainted(false);
        pacienteBoton.setContentAreaFilled(false);
        pacienteBoton.setFocusPainted(false);
        pacienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteBotonActionPerformed(evt);
            }
        });
        jPanel1.add(pacienteBoton);
        pacienteBoton.setBounds(400, 230, 160, 110);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdministrador1.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo);
        fondo.setBounds(-20, -10, 793, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        
        GUI_Login interfazLogin = new GUI_Login();
        interfazLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionMouseClicked

    private void citaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citaBotonActionPerformed
        GUI_InterfazCitas interfazModificarCita = new GUI_InterfazCitas();
        interfazModificarCita.setTipo("Operador");
        interfazModificarCita.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_citaBotonActionPerformed

    private void informesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informesBotonActionPerformed
        GUI_InterfazInformes i = new GUI_InterfazInformes();
        i.setTipo("Operador");
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_informesBotonActionPerformed

    private void pacienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteBotonActionPerformed
        // TODO add your handling code here:
        GUI_InterfazPacientes interfazCrearPaciente = new GUI_InterfazPacientes();
        interfazCrearPaciente.setTipo("Operador");
        interfazCrearPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pacienteBotonActionPerformed
   public void personalizarBienvenida(){
        /*Operador operador = new Operador();
        ControladorOperador controladorOperador = new ControladorOperador();        
        operador = controladorOperador.consultarDatosOperador(cedula); 
        jLabel1.setText(operador.getPrimer_nombre());*/
    }    
    public static void main(String args[]){
        
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run(){
                
                new GUI_Operador().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JButton citaBoton;
    private javax.swing.JLabel citaLabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel informeLabel;
    private javax.swing.JButton informesBoton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel operadorLabel;
    private javax.swing.JLabel operadorLabel2;
    private javax.swing.JButton pacienteBoton;
    private javax.swing.JLabel pacienteLabel;
    // End of variables declaration//GEN-END:variables
   
}