package GUI;

public class GUI_Administrador extends javax.swing.JFrame {
    
    public GUI_Administrador(){
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AreaLabel = new javax.swing.JLabel();
        administradorLabel = new javax.swing.JLabel();
        areaBoton = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JLabel();
        administradorLabel2 = new javax.swing.JLabel();
        bienvenidoLabel = new javax.swing.JLabel();
        medicoLabel = new javax.swing.JLabel();
        medicoBoton = new javax.swing.JButton();
        pacienteLabel = new javax.swing.JLabel();
        pacienteBoton = new javax.swing.JButton();
        citaLabel = new javax.swing.JLabel();
        citaBoton = new javax.swing.JButton();
        medicamentoLabel = new javax.swing.JLabel();
        medicamentoBoton = new javax.swing.JButton();
        registrarCampanaLabel = new javax.swing.JLabel();
        campanaBoton = new javax.swing.JButton();
        camaLabel = new javax.swing.JLabel();
        camaBoton = new javax.swing.JButton();
        informeLabel = new javax.swing.JLabel();
        informesBoton = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(null);

        AreaLabel.setBackground(new java.awt.Color(255, 255, 255));
        AreaLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        AreaLabel.setForeground(new java.awt.Color(108, 101, 247));
        AreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AreaLabel.setText("<html><body> <center>  Areas </center></body></html>");
        jPanel1.add(AreaLabel);
        AreaLabel.setBounds(580, 250, 140, 90);

        administradorLabel.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        administradorLabel.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel.setText("Administrador");
        jPanel1.add(administradorLabel);
        administradorLabel.setBounds(140, 50, 200, 50);

        areaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        areaBoton.setBorder(null);
        areaBoton.setBorderPainted(false);
        areaBoton.setContentAreaFilled(false);
        areaBoton.setFocusPainted(false);
        areaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaBotonActionPerformed(evt);
            }
        });
        jPanel1.add(areaBoton);
        areaBoton.setBounds(570, 240, 160, 110);
        areaBoton.getAccessibleContext().setAccessibleName("Reportes y Consultas");

        CerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(CerrarSesion);
        CerrarSesion.setBounds(610, 60, 120, 30);

        administradorLabel2.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        administradorLabel2.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setText("Administrador");
        jPanel1.add(administradorLabel2);
        administradorLabel2.setBounds(40, 280, 200, 50);

        bienvenidoLabel.setBackground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setText("  Bienvenido ");
        jPanel1.add(bienvenidoLabel);
        bienvenidoLabel.setBounds(40, 240, 200, 50);

        medicoLabel.setBackground(new java.awt.Color(255, 255, 255));
        medicoLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        medicoLabel.setForeground(new java.awt.Color(108, 101, 247));
        medicoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicoLabel.setText("<html><body> <center> Empleados</center></body></html>");
        jPanel1.add(medicoLabel);
        medicoLabel.setBounds(410, 140, 140, 90);

        medicoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        medicoBoton.setBorder(null);
        medicoBoton.setBorderPainted(false);
        medicoBoton.setContentAreaFilled(false);
        medicoBoton.setFocusPainted(false);
        medicoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoBotonActionPerformed(evt);
            }
        });
        jPanel1.add(medicoBoton);
        medicoBoton.setBounds(400, 130, 160, 110);

        pacienteLabel.setBackground(new java.awt.Color(255, 255, 255));
        pacienteLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        pacienteLabel.setForeground(new java.awt.Color(108, 101, 247));
        pacienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pacienteLabel.setText("<html><body> <center>  Pacientes </center></body></html>");
        jPanel1.add(pacienteLabel);
        pacienteLabel.setBounds(580, 140, 140, 90);

        pacienteBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        pacienteBoton.setBorder(null);
        pacienteBoton.setBorderPainted(false);
        pacienteBoton.setContentAreaFilled(false);
        pacienteBoton.setFocusPainted(false);
        pacienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteBotonActionPerformed(evt);
            }
        });
        jPanel1.add(pacienteBoton);
        pacienteBoton.setBounds(570, 130, 160, 110);

        citaLabel.setBackground(new java.awt.Color(255, 255, 255));
        citaLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        citaLabel.setForeground(new java.awt.Color(108, 101, 247));
        citaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        citaLabel.setText("<html><body> <center>  Citas </center></body></html>");
        jPanel1.add(citaLabel);
        citaLabel.setBounds(320, 370, 140, 90);

        citaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        citaBoton.setBorder(null);
        citaBoton.setBorderPainted(false);
        citaBoton.setContentAreaFilled(false);
        citaBoton.setFocusPainted(false);
        citaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citaBotonActionPerformed(evt);
            }
        });
        jPanel1.add(citaBoton);
        citaBoton.setBounds(310, 360, 160, 110);

        medicamentoLabel.setBackground(new java.awt.Color(255, 255, 255));
        medicamentoLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        medicamentoLabel.setForeground(new java.awt.Color(108, 101, 247));
        medicamentoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicamentoLabel.setText("<html><body> <center> Medicamentos</center></body></html>");
        jPanel1.add(medicamentoLabel);
        medicamentoLabel.setBounds(490, 370, 150, 90);

        medicamentoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        medicamentoBoton.setBorder(null);
        medicamentoBoton.setBorderPainted(false);
        medicamentoBoton.setContentAreaFilled(false);
        medicamentoBoton.setFocusPainted(false);
        medicamentoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentoBotonActionPerformed(evt);
            }
        });
        jPanel1.add(medicamentoBoton);
        medicamentoBoton.setBounds(480, 360, 170, 110);

        registrarCampanaLabel.setBackground(new java.awt.Color(255, 255, 255));
        registrarCampanaLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        registrarCampanaLabel.setForeground(new java.awt.Color(108, 101, 247));
        registrarCampanaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarCampanaLabel.setText("<html><body> <center> Campañas </center></body></html>");
        jPanel1.add(registrarCampanaLabel);
        registrarCampanaLabel.setBounds(240, 140, 140, 90);

        campanaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        campanaBoton.setBorder(null);
        campanaBoton.setBorderPainted(false);
        campanaBoton.setContentAreaFilled(false);
        campanaBoton.setFocusPainted(false);
        campanaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campanaBotonActionPerformed(evt);
            }
        });
        jPanel1.add(campanaBoton);
        campanaBoton.setBounds(230, 130, 160, 110);

        camaLabel.setBackground(new java.awt.Color(255, 255, 255));
        camaLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        camaLabel.setForeground(new java.awt.Color(108, 101, 247));
        camaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        camaLabel.setText("<html><body> <center> Camas </center></body></html>");
        jPanel1.add(camaLabel);
        camaLabel.setBounds(240, 250, 140, 90);

        camaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        camaBoton.setBorder(null);
        camaBoton.setBorderPainted(false);
        camaBoton.setContentAreaFilled(false);
        camaBoton.setFocusPainted(false);
        camaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camaBotonActionPerformed(evt);
            }
        });
        jPanel1.add(camaBoton);
        camaBoton.setBounds(230, 240, 160, 110);

        informeLabel.setBackground(new java.awt.Color(255, 255, 255));
        informeLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        informeLabel.setForeground(new java.awt.Color(108, 101, 247));
        informeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informeLabel.setText("<html><body> <center>  Informes </center></body></html>");
        jPanel1.add(informeLabel);
        informeLabel.setBounds(410, 250, 140, 90);

        informesBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        informesBoton.setBorder(null);
        informesBoton.setBorderPainted(false);
        informesBoton.setContentAreaFilled(false);
        informesBoton.setFocusPainted(false);
        informesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informesBotonActionPerformed(evt);
            }
        });
        jPanel1.add(informesBoton);
        informesBoton.setBounds(400, 240, 160, 110);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdministrador1.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 760, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void areaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaBotonActionPerformed
        
        GUI_InterfazAreas med = new GUI_InterfazAreas();
        med.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_areaBotonActionPerformed
      
    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        
        GUI_Login interfazLogin = new GUI_Login();
        interfazLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionMouseClicked
    
    private void medicoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoBotonActionPerformed
       
        GUI_InterfazEmpleados interfazCrearMedico = new GUI_InterfazEmpleados();
        interfazCrearMedico.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_medicoBotonActionPerformed

    private void pacienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteBotonActionPerformed
        // TODO add your handling code here:
        GUI_InterfazPacientes interfazCrearPaciente = new GUI_InterfazPacientes();
        interfazCrearPaciente.setTipo("Administrador");
        interfazCrearPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pacienteBotonActionPerformed

    private void citaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citaBotonActionPerformed
        GUI_InterfazCitas interfazModificarCita = new GUI_InterfazCitas();
        interfazModificarCita.setTipo("Administrador");
        interfazModificarCita.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_citaBotonActionPerformed

    private void medicamentoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentoBotonActionPerformed
        GUI_InterfazMedicamentos i = new GUI_InterfazMedicamentos();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_medicamentoBotonActionPerformed

    private void campanaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campanaBotonActionPerformed
        GUI_InterfazCampana i = new GUI_InterfazCampana();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_campanaBotonActionPerformed

    private void camaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camaBotonActionPerformed
        GUI_InterfazCamas i = new GUI_InterfazCamas();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_camaBotonActionPerformed

    private void informesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informesBotonActionPerformed
        GUI_InterfazInformes i = new GUI_InterfazInformes();
        i.setTipo("Administrador");
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_informesBotonActionPerformed
    
    public static void main(String args[]){
       
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run(){
                
                new GUI_Administrador().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AreaLabel;
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel administradorLabel;
    private javax.swing.JLabel administradorLabel2;
    private javax.swing.JButton areaBoton;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JButton camaBoton;
    private javax.swing.JLabel camaLabel;
    private javax.swing.JButton campanaBoton;
    private javax.swing.JButton citaBoton;
    private javax.swing.JLabel citaLabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel informeLabel;
    private javax.swing.JButton informesBoton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton medicamentoBoton;
    private javax.swing.JLabel medicamentoLabel;
    private javax.swing.JButton medicoBoton;
    private javax.swing.JLabel medicoLabel;
    private javax.swing.JButton pacienteBoton;
    private javax.swing.JLabel pacienteLabel;
    private javax.swing.JLabel registrarCampanaLabel;
    // End of variables declaration//GEN-END:variables
}