package GUI;

public class GUI_InterfazAreas extends javax.swing.JFrame {
    
    public GUI_InterfazAreas(){
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        crearAreaLabel = new javax.swing.JLabel();
        administradorLabel = new javax.swing.JLabel();
        crearArea = new javax.swing.JButton();
        CerrarSesion = new javax.swing.JLabel();
        administradorLabel2 = new javax.swing.JLabel();
        bienvenidoLabel = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        crearAreaLabel1 = new javax.swing.JLabel();
        crearArea1 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(null);

        crearAreaLabel.setBackground(new java.awt.Color(255, 255, 255));
        crearAreaLabel.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        crearAreaLabel.setForeground(new java.awt.Color(108, 101, 247));
        crearAreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearAreaLabel.setText("<html><body> <center>  Crear<br>Area </center></body></html>");
        jPanel1.add(crearAreaLabel);
        crearAreaLabel.setBounds(270, 260, 140, 90);

        administradorLabel.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        administradorLabel.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel.setText("Areas");
        jPanel1.add(administradorLabel);
        administradorLabel.setBounds(140, 50, 200, 50);

        crearArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        crearArea.setBorder(null);
        crearArea.setBorderPainted(false);
        crearArea.setContentAreaFilled(false);
        crearArea.setFocusPainted(false);
        crearArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAreaActionPerformed(evt);
            }
        });
        jPanel1.add(crearArea);
        crearArea.setBounds(260, 250, 160, 110);
        crearArea.getAccessibleContext().setAccessibleName("Reportes y Consultas");

        CerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(CerrarSesion);
        CerrarSesion.setBounds(610, 60, 120, 30);

        administradorLabel2.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        administradorLabel2.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setText("Administrador");
        jPanel1.add(administradorLabel2);
        administradorLabel2.setBounds(40, 280, 200, 50);

        bienvenidoLabel.setBackground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setText("  Bienvenido ");
        jPanel1.add(bienvenidoLabel);
        bienvenidoLabel.setBounds(40, 240, 200, 50);

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelarMed.png"))); // NOI18N
        botonCancelar.setBorder(null);
        botonCancelar.setBorderPainted(false);
        botonCancelar.setContentAreaFilled(false);
        botonCancelar.setFocusPainted(false);
        botonCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelarPeq.png"))); // NOI18N
        botonCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar);
        botonCancelar.setBounds(610, 400, 130, 70);

        crearAreaLabel1.setBackground(new java.awt.Color(255, 255, 255));
        crearAreaLabel1.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        crearAreaLabel1.setForeground(new java.awt.Color(108, 101, 247));
        crearAreaLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearAreaLabel1.setText("<html><body> <center>  Modificar<br>Area </center></body></html>");
        jPanel1.add(crearAreaLabel1);
        crearAreaLabel1.setBounds(450, 260, 140, 90);

        crearArea1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        crearArea1.setBorder(null);
        crearArea1.setBorderPainted(false);
        crearArea1.setContentAreaFilled(false);
        crearArea1.setFocusPainted(false);
        crearArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearArea1ActionPerformed(evt);
            }
        });
        jPanel1.add(crearArea1);
        crearArea1.setBounds(440, 250, 160, 110);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdministrador1.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 760, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void crearAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAreaActionPerformed
        
        GUI_CrearArea med = new GUI_CrearArea();
        med.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearAreaActionPerformed
      
    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        
        GUI_Login interfazLogin = new GUI_Login();
        interfazLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionMouseClicked

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        GUI_Administrador adminLogin = new GUI_Administrador();
        adminLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void crearArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearArea1ActionPerformed
        GUI_ModificarArea interfazLogin = new GUI_ModificarArea();
        interfazLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearArea1ActionPerformed
        
    public static void main(String args[]){
       
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run(){
                
                new GUI_InterfazAreas().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel administradorLabel;
    private javax.swing.JLabel administradorLabel2;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton crearArea;
    private javax.swing.JButton crearArea1;
    private javax.swing.JLabel crearAreaLabel;
    private javax.swing.JLabel crearAreaLabel1;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}