package GUI;

public class GUI_InterfazMedicamentos extends javax.swing.JFrame {
    
    public GUI_InterfazMedicamentos(){
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        administradorLabel = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JLabel();
        administradorLabel2 = new javax.swing.JLabel();
        bienvenidoLabel = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        crearPacienteLabel1 = new javax.swing.JLabel();
        registrarMedicamento = new javax.swing.JButton();
        modificarPacienteLabel1 = new javax.swing.JLabel();
        modificarMedicamento = new javax.swing.JButton();
        crearPacienteLabel2 = new javax.swing.JLabel();
        registrarCausa = new javax.swing.JButton();
        crearPacienteLabel3 = new javax.swing.JLabel();
        modificarCausa = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(null);

        administradorLabel.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        administradorLabel.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel.setText("Medicamentos");
        jPanel1.add(administradorLabel);
        administradorLabel.setBounds(140, 50, 200, 50);

        CerrarSesion.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setText("Cerrar Sesión");
        CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(CerrarSesion);
        CerrarSesion.setBounds(610, 60, 120, 30);

        administradorLabel2.setBackground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        administradorLabel2.setForeground(new java.awt.Color(255, 255, 255));
        administradorLabel2.setText("Administrador");
        jPanel1.add(administradorLabel2);
        administradorLabel2.setBounds(40, 280, 200, 50);

        bienvenidoLabel.setBackground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setFont(new java.awt.Font("SansSerif", 0, 26)); // NOI18N
        bienvenidoLabel.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidoLabel.setText("  Bienvenido ");
        jPanel1.add(bienvenidoLabel);
        bienvenidoLabel.setBounds(40, 240, 200, 50);

        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelarMed.png"))); // NOI18N
        botonCancelar.setBorder(null);
        botonCancelar.setBorderPainted(false);
        botonCancelar.setContentAreaFilled(false);
        botonCancelar.setFocusPainted(false);
        botonCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CancelarPeq.png"))); // NOI18N
        botonCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar);
        botonCancelar.setBounds(610, 420, 130, 70);

        crearPacienteLabel1.setBackground(new java.awt.Color(255, 255, 255));
        crearPacienteLabel1.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        crearPacienteLabel1.setForeground(new java.awt.Color(108, 101, 247));
        crearPacienteLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearPacienteLabel1.setText("<html><body> <center>  Registrar<br>Medicamento </center></body></html>");
        jPanel1.add(crearPacienteLabel1);
        crearPacienteLabel1.setBounds(310, 190, 140, 90);

        registrarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        registrarMedicamento.setBorder(null);
        registrarMedicamento.setBorderPainted(false);
        registrarMedicamento.setContentAreaFilled(false);
        registrarMedicamento.setFocusPainted(false);
        registrarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMedicamentoActionPerformed(evt);
            }
        });
        jPanel1.add(registrarMedicamento);
        registrarMedicamento.setBounds(300, 180, 160, 110);

        modificarPacienteLabel1.setBackground(new java.awt.Color(255, 255, 255));
        modificarPacienteLabel1.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        modificarPacienteLabel1.setForeground(new java.awt.Color(108, 101, 247));
        modificarPacienteLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificarPacienteLabel1.setText("<html><body> <center>  Modificar<br>Medicamento </center></body></html>");
        jPanel1.add(modificarPacienteLabel1);
        modificarPacienteLabel1.setBounds(520, 190, 140, 90);

        modificarMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        modificarMedicamento.setBorder(null);
        modificarMedicamento.setBorderPainted(false);
        modificarMedicamento.setContentAreaFilled(false);
        modificarMedicamento.setFocusPainted(false);
        modificarMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMedicamentoActionPerformed(evt);
            }
        });
        jPanel1.add(modificarMedicamento);
        modificarMedicamento.setBounds(510, 180, 160, 110);

        crearPacienteLabel2.setBackground(new java.awt.Color(255, 255, 255));
        crearPacienteLabel2.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        crearPacienteLabel2.setForeground(new java.awt.Color(108, 101, 247));
        crearPacienteLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearPacienteLabel2.setText("<html><body> <center>  Registrar<br>Causas </center></body></html>");
        jPanel1.add(crearPacienteLabel2);
        crearPacienteLabel2.setBounds(310, 330, 140, 90);

        registrarCausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        registrarCausa.setBorder(null);
        registrarCausa.setBorderPainted(false);
        registrarCausa.setContentAreaFilled(false);
        registrarCausa.setFocusPainted(false);
        registrarCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCausaActionPerformed(evt);
            }
        });
        jPanel1.add(registrarCausa);
        registrarCausa.setBounds(300, 320, 160, 110);

        crearPacienteLabel3.setBackground(new java.awt.Color(255, 255, 255));
        crearPacienteLabel3.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        crearPacienteLabel3.setForeground(new java.awt.Color(108, 101, 247));
        crearPacienteLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearPacienteLabel3.setText("<html><body> <center>  Modificar<br>Causas </center></body></html>");
        jPanel1.add(crearPacienteLabel3);
        crearPacienteLabel3.setBounds(520, 330, 140, 90);

        modificarCausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoBotones.png"))); // NOI18N
        modificarCausa.setBorder(null);
        modificarCausa.setBorderPainted(false);
        modificarCausa.setContentAreaFilled(false);
        modificarCausa.setFocusPainted(false);
        modificarCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarCausaActionPerformed(evt);
            }
        });
        jPanel1.add(modificarCausa);
        modificarCausa.setBounds(510, 320, 160, 110);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdministrador1.png"))); // NOI18N
        fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 760, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
          
    private void CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarSesionMouseClicked
        
        GUI_Login interfazLogin = new GUI_Login();
        interfazLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CerrarSesionMouseClicked
    
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed

        GUI_Administrador adminLogin = new GUI_Administrador();
        adminLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void registrarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMedicamentoActionPerformed
        // TODO add your handling code here:
        GUI_CrearMedicamento interfazCrearPaciente = new GUI_CrearMedicamento();
        interfazCrearPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarMedicamentoActionPerformed

    private void modificarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMedicamentoActionPerformed
        // TODO add your handling code here:
        GUI_ModificarMedicamento interfazModificarPaciente = new GUI_ModificarMedicamento();
        interfazModificarPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarMedicamentoActionPerformed

    private void registrarCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCausaActionPerformed
        // TODO add your handling code here:
        GUI_CrearCausa interfazModificarPaciente = new GUI_CrearCausa();
        interfazModificarPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarCausaActionPerformed

    private void modificarCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarCausaActionPerformed
        GUI_ModificarCausa interfazModificarPaciente = new GUI_ModificarCausa();
        interfazModificarPaciente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_modificarCausaActionPerformed
    
    public static void main(String args[]){
       
        java.awt.EventQueue.invokeLater(new Runnable(){
            
            public void run(){
                
                new GUI_InterfazMedicamentos().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel administradorLabel;
    private javax.swing.JLabel administradorLabel2;
    private javax.swing.JLabel bienvenidoLabel;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel crearPacienteLabel1;
    private javax.swing.JLabel crearPacienteLabel2;
    private javax.swing.JLabel crearPacienteLabel3;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarCausa;
    private javax.swing.JButton modificarMedicamento;
    private javax.swing.JLabel modificarPacienteLabel1;
    private javax.swing.JButton registrarCausa;
    private javax.swing.JButton registrarMedicamento;
    // End of variables declaration//GEN-END:variables
}